site_name: Donut Finder API
site_url: https://mydomain.org/mysite

nav:
  - Welcome: index.md
  - Quickstart:
      - Installation: Quickstart/installation.md
      - Send your first request: Quickstart/quickstart.md
  - Reference:
      - Donut Store:
          - Overview: Reference/donut-store/index.md
      - Donut Type:
          - Overview: Reference/donut-type/index.md
      - Handling Errors:
          - Overview: Reference/handling-errors/index.md
  - Tutorial:
      - Donut Store:
        - Filter Store by Location: tutorials/donut-store/filter-store-by-location.md
        - Search Store by Name: tutorials/donut-store/search-store-by-name.md
      - Donut Type:
        - Search Donut Types by Name: tutorials/donut-type/search-donut-types-by-name.md
  - Changelog: 
      - What's New?: Changelog/changelog.md
  - Support:
      - FAQ: Support/faq.md
      - Community: Support/community.md


theme:
  name: material
  features:
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.sections
    - navigation.indexes
    - toc.follow
    

  language: en
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg



extra_css:
  - custom.css

extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Deutsch
      link: /de/
      lang: de

copyright: Copyright &copy; 2024 <a href="https://github.com/Aviatorscode2" target="_blank" rel="noopener">Victor Yakubu</a>